### ISSUE TITLE
improve nameing

### ISSUE THREAD

**Issue by damoon** [utopia-planitia/chart-prettier#9]
ObjectBucketClaim becomes objectbucketclaim

Better would be object-bucket-claim

**Comment by damoon** [comment]
two objects with the same kind and name,
one with a namespace the other without
create the name a-b-

**Comment by damoon** [comment]
maybe start with name and then type?
use some kind of folder structure?

**Comment by elchenberg** [comment]
Or maybe use the kustomize naming?

For example `objectbucket.io_v1alpha1_objectbucketclaim_obc-name.yaml` for

```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-name
spec:
  generateBucketName: obc-generate-bucket-name
```

And `default_objectbucket.io_v1alpha1_objectbucketclaim_obc-name.yaml` and `test_objectbucket.io_v1alpha1_objectbucketclaim_obc-name.yaml` for

```yaml
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-name
spec:
  generateBucketName: obc-generate-bucket-name
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-name
  namespace: test
spec:
  generateBucketName: obc-generate-bucket-name
```
